In [2]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [ ]:
a + b


In [12]:
import numpy as np


In [13]:
vect_a= np.array(a)
vect_b= np.array(b)

In [14]:
vect_a+vect_b

array([ 7,  9, 11, 13, 15])

In [15]:
d = [6, 8]
vect_d = np.array(d)

In [17]:
np.linalg.norm(vect_a)

7.416198487095663

In [18]:
np.linalg.norm(vect_d)

10.0

In [19]:
np.linalg.norm(vect_d,2)

10.0

In [20]:
np.linalg.norm(vect_d,1)

14.0

In [22]:
vect_d-10

array([-4, -2])

In [31]:
vect_a=np.array([2,4,6])
vect_b=np.array([2,3,4])

In [32]:
vect_a+vect_b

array([ 4,  7, 10])

In [35]:
#perkalian dengan scalar

vect_a * 0.5

array([1., 2., 3.])

In [36]:
vect_a*vect_b

array([ 4, 12, 24])

In [40]:
vect_a.dot(vect_b)

40

In [44]:
result_dot_product = vect_a.dot(vect_b)
result_dot_product

40

In [41]:
print(vect_a)
print(vect_b)

[2 4 6]
[2 3 4]


In [42]:
vect_a = np.array([5,0])
vect_b = np.array([8,0])

In [43]:
vect_a

array([5, 0])

In [46]:
cos_theta=result_dot_product/(np.linalg.norm(vect_a)* np.linalg.norm(vect_b))

In [47]:
cos_theta

1.0